# CONFIGURAÇÃO DO H2 (PARA QUEM TEM PREGUIÇA DE SUBIR DOCKER)
spring.datasource.url=jdbc:h2:mem:mercadoJJJ
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# DIALETO CORRETO, SEU ESTRUME!
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# HABILITA O CONSOLE (Pra você ver as tabelas no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# HIBERNATE CRIA TUDO DO ZERO SEMPRE
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true