# CONFIGURAÇÃO DO H2 (PARA QUEM TEM PREGUIÇA DE SUBIR DOCKER)
spring.datasource.url=jdbc:h2:mem:mercadoJJJ
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# DIALETO CORRETO, SEU ESTRUME!
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# HABILITA O CONSOLE (Pra você ver as tabelas no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# HIBERNATE CRIA TUDO DO ZERO SEMPRE
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Define o caminho da UI do Swagger (Tenta acessar por aqui depois)
springdoc.swagger-ui.path=/swagger-ui.html

# Define onde o JSON do OpenAPI vai ser gerado
springdoc.api-docs.path=/v3/api-docs

# Habilita a visualização da interface (Garante que essa porra tá ligada)
springdoc.swagger-ui.enabled=true